---
extends:
- eslint:recommended
# - plugin:react/recommended
# plugins:
# - react
env:
  browser: true
  es6: true
  node: true
  jest: true
globals:
  process: true
  fetch: true
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    # jsx: true
    experimentalObjectRestSpread: true
rules:
  no-console: 0
  no-undef: 1
  no-unused-vars: 1
  eqeqeq:
  - 2
  - smart
  no-floating-decimal: 2
  no-multi-spaces:
  - 0
  - exceptions:
    ImportDeclaration: true
    VariableDeclarator: true
  no-multi-str: 2
  camelcase:
    - 1
    - properties: never
  eol-last: 1
  indent:
  - 2
  - 2
  - SwitchCase: 1
    VariableDeclarator: 1
  quotes:
  - 2
  - single
  - avoid-escape
  semi: 2
  space-before-blocks: 2
  space-before-function-paren:
  - 2
  - never
  constructor-super: 2
  arrow-spacing: 2
  # react/prop-types:
  # - 1
  # - skipUndeclared: true
